import type { Metadata } from "next";
import { Raleway } from "next/font/google";
import "@mantine/core/styles.css";

import "./globals.css";
import { ColorSchemeScript, MantineProvider } from "@mantine/core";

const font = Raleway({
	variable: "--font-geist-mono",
	subsets: ["latin"],
});

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en" suppressHydrationWarning>
			<head>
				<ColorSchemeScript />
			</head>
			<body className={`${font.variable} antialiased`}>
				<MantineProvider>{children}</MantineProvider>
			</body>
		</html>
	);
}
